-- supabase/seed.sql
-- 32 seed questions: 8 per category. Mirrors src/lib/mockData.ts.

-- ── Quiz Challenge ────────────────────────────────────────────────────
insert into public.questions (category, question_text, options, correct_answer, explanation) values
('quiz', 'Who is known as the chief architect of the Indian Constitution?',
 '["Jawaharlal Nehru","Dr. B. R. Ambedkar","Sardar Vallabhbhai Patel","Rajendra Prasad"]'::jsonb,
 'Dr. B. R. Ambedkar',
 'Dr. B. R. Ambedkar chaired the Drafting Committee of the Constituent Assembly.'),
('quiz', 'The Indian Constitution came into effect on which date?',
 '["15 August 1947","26 January 1950","26 November 1949","2 October 1948"]'::jsonb,
 '26 January 1950',
 'It was adopted on 26 November 1949 and came into force on 26 January 1950 — celebrated as Republic Day.'),
('quiz', 'Who led the Salt March to Dandi in 1930?',
 '["Subhas Chandra Bose","Bhagat Singh","Mahatma Gandhi","Lala Lajpat Rai"]'::jsonb,
 'Mahatma Gandhi',
 'The 240-mile march protested the British salt tax and sparked nationwide civil disobedience.'),
('quiz', '"A leader is one who knows the way, goes the way, and shows the way." Who said this?',
 '["John C. Maxwell","Nelson Mandela","Winston Churchill","Simon Sinek"]'::jsonb,
 'John C. Maxwell',
 'John C. Maxwell is an author known for his books on leadership.'),
('quiz', 'Who was the first woman Prime Minister of India?',
 '["Sarojini Naidu","Indira Gandhi","Sucheta Kripalani","Vijaya Lakshmi Pandit"]'::jsonb,
 'Indira Gandhi',
 'Indira Gandhi became Prime Minister in 1966.'),
('quiz', 'Nelson Mandela spent 27 years in prison before leading which country?',
 '["Kenya","Ghana","South Africa","Nigeria"]'::jsonb,
 'South Africa',
 'Mandela became South Africa''s first democratically elected president in 1994.'),
('quiz', 'Which fundamental right is called the "heart and soul" of the Indian Constitution?',
 '["Right to Equality","Right to Freedom","Right to Constitutional Remedies","Right against Exploitation"]'::jsonb,
 'Right to Constitutional Remedies',
 'Dr. Ambedkar described Article 32 as the heart and soul of the Constitution.'),
('quiz', '"Be the change you wish to see in the world" is popularly attributed to whom?',
 '["Rabindranath Tagore","Mahatma Gandhi","Swami Vivekananda","APJ Abdul Kalam"]'::jsonb,
 'Mahatma Gandhi',
 'Widely attributed to Gandhi, it captures his philosophy of personal responsibility.');

-- ── Guess the Leader ──────────────────────────────────────────────────
-- image_url left null — upload real portraits via the admin Media page.
insert into public.questions (category, question_text, options, correct_answer, explanation) values
('guess_leader', 'Who is this?',
 '["Dr. APJ Abdul Kalam","C. V. Raman","Homi Bhabha","Vikram Sarabhai"]'::jsonb,
 'Dr. APJ Abdul Kalam',
 'The ''Missile Man of India'' and 11th President, beloved for inspiring students.'),
('guess_leader', 'Who is this?',
 '["Kiran Bedi","Indra Nooyi","Sudha Murty","Falguni Nayar"]'::jsonb,
 'Sudha Murty',
 'Author, philanthropist, and founding trustee of the Infosys Foundation.'),
('guess_leader', 'Who is this?',
 '["Ratan Tata","Narayana Murthy","Azim Premji","Dhirubhai Ambani"]'::jsonb,
 'Ratan Tata',
 'Industrialist and philanthropist who led the Tata Group for over two decades.'),
('guess_leader', 'Who is this?',
 '["Rosa Parks","Malala Yousafzai","Greta Thunberg","Kamala Harris"]'::jsonb,
 'Malala Yousafzai',
 'The youngest Nobel Peace Prize laureate, an advocate for girls'' education.'),
('guess_leader', 'Who is this?',
 '["Sardar Vallabhbhai Patel","Jawaharlal Nehru","Rajendra Prasad","Lal Bahadur Shastri"]'::jsonb,
 'Sardar Vallabhbhai Patel',
 'The ''Iron Man of India'' who unified over 560 princely states.'),
('guess_leader', 'Who is this?',
 '["Mother Teresa","Sarojini Naidu","Annie Besant","Kasturba Gandhi"]'::jsonb,
 'Mother Teresa',
 'Founder of the Missionaries of Charity, Nobel Peace Prize laureate 1979.'),
('guess_leader', 'Who is this?',
 '["Mary Kom","P. V. Sindhu","Saina Nehwal","Mithali Raj"]'::jsonb,
 'Mary Kom',
 'Six-time world champion boxer and Olympic medallist from Manipur.'),
('guess_leader', 'Who is this?',
 '["Nelson Mandela","Martin Luther King Jr.","Desmond Tutu","Kofi Annan"]'::jsonb,
 'Nelson Mandela',
 'Anti-apartheid leader and South Africa''s first democratically elected president.');

-- ── Match the Pair ────────────────────────────────────────────────────
insert into public.questions (category, question_text, pairs) values
('match_pair', 'Match each leader with their achievement.',
 '[{"left":"Dr. B. R. Ambedkar","right":"Chief architect of the Indian Constitution"},{"left":"Mother Teresa","right":"Founded the Missionaries of Charity"},{"left":"Dr. APJ Abdul Kalam","right":"Led India''s missile development programme"},{"left":"Sardar Patel","right":"Unified the princely states of India"}]'::jsonb),
('match_pair', 'Match each leader with their movement or milestone.',
 '[{"left":"Mahatma Gandhi","right":"Salt March to Dandi"},{"left":"Nelson Mandela","right":"Ended apartheid in South Africa"},{"left":"Martin Luther King Jr.","right":"\"I Have a Dream\" speech"},{"left":"Malala Yousafzai","right":"Youngest Nobel Peace Prize laureate"}]'::jsonb),
('match_pair', 'Match each Indian pioneer with their field.',
 '[{"left":"C. V. Raman","right":"Nobel Prize in Physics"},{"left":"Vikram Sarabhai","right":"Father of the Indian space programme"},{"left":"Verghese Kurien","right":"The White Revolution (Operation Flood)"},{"left":"M. S. Swaminathan","right":"The Green Revolution in India"}]'::jsonb),
('match_pair', 'Match each business leader with their organisation.',
 '[{"left":"Narayana Murthy","right":"Co-founded Infosys"},{"left":"Ratan Tata","right":"Chaired the Tata Group"},{"left":"Kiran Mazumdar-Shaw","right":"Founded Biocon"},{"left":"Azim Premji","right":"Built Wipro into an IT leader"}]'::jsonb),
('match_pair', 'Match each leader with their famous words.',
 '[{"left":"Mahatma Gandhi","right":"\"Be the change you wish to see\""},{"left":"APJ Abdul Kalam","right":"\"Dream, dream, dream\""},{"left":"Swami Vivekananda","right":"\"Arise, awake, and stop not\""},{"left":"Nelson Mandela","right":"\"It always seems impossible until it''s done\""}]'::jsonb),
('match_pair', 'Match each sports leader with their sport.',
 '[{"left":"Mary Kom","right":"Boxing"},{"left":"M. S. Dhoni","right":"Cricket"},{"left":"P. V. Sindhu","right":"Badminton"},{"left":"Viswanathan Anand","right":"Chess"}]'::jsonb),
('match_pair', 'Match each freedom fighter with what they are remembered for.',
 '[{"left":"Rani Lakshmibai","right":"Led the defence of Jhansi in 1857"},{"left":"Bhagat Singh","right":"Revolutionary who inspired India''s youth"},{"left":"Subhas Chandra Bose","right":"Founded the Indian National Army"},{"left":"Sarojini Naidu","right":"The Nightingale of India"}]'::jsonb),
('match_pair', 'Match each world leader with their country.',
 '[{"left":"Nelson Mandela","right":"South Africa"},{"left":"Abraham Lincoln","right":"United States"},{"left":"Jacinda Ardern","right":"New Zealand"},{"left":"Lee Kuan Yew","right":"Singapore"}]'::jsonb);

-- ── Leadership Scenario ───────────────────────────────────────────────
insert into public.questions (category, question_text, options, correct_answer, explanation) values
('leadership_scenario', 'Your project team''s presentation is tomorrow, and a teammate who was assigned a key section says they''re overwhelmed and haven''t started. What do you do?',
 '["Tell the professor the teammate didn''t do their part","Sit with them tonight, split the section, and help them finish it","Do the whole section yourself without telling anyone","Suggest the team presents without that section"]'::jsonb,
 'Sit with them tonight, split the section, and help them finish it',
 'Great leaders support teammates under pressure instead of blaming or bypassing them.'),
('leadership_scenario', 'During a club event you organised, the sound system fails in front of a full audience. What''s your first move?',
 '["Find whoever set up the system and ask what went wrong","Calmly address the audience, buy time with an activity, and send someone to fix it","Cancel the event and apologise","Wait quietly for the technical team to notice"]'::jsonb,
 'Calmly address the audience, buy time with an activity, and send someone to fix it',
 'Composure and quick delegation keep the situation moving — blame can wait.'),
('leadership_scenario', 'You notice a first-year student sitting alone at every club meeting, never speaking up. As a senior member, what do you do?',
 '["Leave them alone — they''ll open up eventually","Point them out in the meeting and ask them to speak","Sit with them, learn their interests, and connect them to a small task they''d enjoy","Tell the club head someone isn''t participating"]'::jsonb,
 'Sit with them, learn their interests, and connect them to a small task they''d enjoy',
 'Inclusive leaders create belonging through personal connection, not public pressure.'),
('leadership_scenario', 'Your team made an error in the event budget, and you signed off on it. The coordinator asks what happened. What do you say?',
 '["Explain that a teammate made the calculation error","Own the mistake as the person who approved it, and present a fix","Say the budget format was confusing","Promise it won''t happen again without explaining"]'::jsonb,
 'Own the mistake as the person who approved it, and present a fix',
 'Accountability means owning outcomes you approved — and pairing honesty with a solution.'),
('leadership_scenario', 'Two of your closest friends on the team have a heated disagreement about the event theme, and both want you to take their side. What do you do?',
 '["Side with the friend whose idea you prefer","Stay out of it completely","Hear both out together, find shared goals, and guide them to a combined solution","Ask the faculty coordinator to decide"]'::jsonb,
 'Hear both out together, find shared goals, and guide them to a combined solution',
 'Mediating openly beats taking sides — leaders turn conflict into collaboration.'),
('leadership_scenario', 'You have an exam in three days, but your club''s flagship event — which you lead — is the day before. A volunteer offers to take over some coordination. What do you do?',
 '["Refuse — a leader should handle everything personally","Hand over everything and focus only on the exam","Delegate clear responsibilities with a checklist, stay reachable, and protect study time","Skip preparing for the exam"]'::jsonb,
 'Delegate clear responsibilities with a checklist, stay reachable, and protect study time',
 'Delegation with clarity is a leadership skill — doing everything yourself isn''t.'),
('leadership_scenario', 'In a group discussion, one member keeps interrupting others and dominating. The quieter members have stopped contributing. As the discussion lead, what do you do?',
 '["Let it continue — confident voices deserve the floor","Publicly tell the person to stop talking","Thank them for their energy, then deliberately invite each quiet member to share","End the discussion early"]'::jsonb,
 'Thank them for their energy, then deliberately invite each quiet member to share',
 'Redirecting without humiliating keeps everyone engaged — good facilitators balance voices.'),
('leadership_scenario', 'You discover the event poster your team published has a factual error, but it already has hundreds of shares. What do you do?',
 '["Ignore it — most people won''t notice","Quietly delete the post and repost the corrected version","Post a clear correction, thank those who pointed it out, and update the poster","Blame the design team in the group chat"]'::jsonb,
 'Post a clear correction, thank those who pointed it out, and update the poster',
 'Transparent correction builds more trust than quiet deletion ever could.');
